In [47]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [31]:
df = pd.read_csv("spam.csv", encoding="latin-1")

In [13]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [14]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [15]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [16]:
df['spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [17]:
df

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham             Will Ã_ b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [18]:
new_df = pd.read_csv('spam.csv')

In [19]:
new_df['Category'].replace({'ham':0,'spam':1},inplace=True)

In [20]:
new_df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [22]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [24]:
df.shape

(5572, 3)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.25)

In [28]:
X_test.shape

(1393,)

#### Create bag of words representation using CountVectorizer

In [60]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [ ]:
X_train

909     January Male Sale! Hot Gay chat now cheaper, c...
3482    Hello, my love! How goes that day ? I wish you...
5441    By the way, make sure u get train to worc fore...
4054    When is school starting. Where will you stay. ...
1787                           Yes:)sura in sun tv.:)lol.
                              ...
4873                     Wat happened to the cruise thing
1722    Thought praps you meant another one. Goodo! I'...
1266      \Hey sorry I didntgive ya a a bellearlier hunny
3419    As a valued customer, I am pleased to advise y...
3123    My uncles in Atlanta. Wish you guys a great se...
Name: Message, Length: 4179, dtype: object

In [33]:
X_train_cv

<4179x7555 sparse matrix of type '<class 'numpy.int64'>'
	with 55639 stored elements in Compressed Sparse Row format>

In [34]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [35]:
X_train_cv.shape

(4179, 7555)

In [ ]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'âªt', 'âªve', 'â¼1'], dtype=object)

In [37]:
v.get_feature_names_out()[1221]

'batt'

In [38]:
v.vocabulary_

{'january': 3683,
 'male': 4211,
 'sale': 5731,
 'hot': 3411,
 'gay': 3017,
 'chat': 1709,
 'now': 4715,
 'cheaper': 1715,
 'call': 1572,
 '08709222922': 88,
 'national': 4575,
 'rate': 5421,
 'from': 2952,
 '5p': 548,
 'min': 4360,
 'cheap': 1714,
 'to': 6755,
 '8p': 702,
 'peak': 4996,
 'stop': 6321,
 'texts': 6622,
 '08712460324': 105,
 '10p': 259,
 'hello': 3308,
 'my': 4541,
 'love': 4108,
 'how': 3422,
 'goes': 3092,
 'that': 6637,
 'day': 2135,
 'wish': 7351,
 'your': 7517,
 'well': 7269,
 'and': 939,
 'fine': 2795,
 'babe': 1159,
 'hope': 3392,
 'you': 7511,
 'find': 2792,
 'some': 6129,
 'job': 3718,
 'prospects': 5319,
 'miss': 4388,
 'boytoy': 1441,
 'teasing': 6571,
 'kiss': 3837,
 'by': 1553,
 'the': 6643,
 'way': 7229,
 'make': 4204,
 'sure': 6449,
 'get': 3044,
 'train': 6830,
 'worc': 7396,
 'foregate': 2875,
 'street': 6339,
 'not': 4704,
 'shrub': 5973,
 'hill': 3340,
 'have': 3267,
 'fun': 2970,
 'night': 4650,
 'when': 7295,
 'is': 3633,
 'school': 5781,
 'starting': 6273,
 'where': 7299,
 'will': 7330,
 'stay': 6283,
 'what': 7290,
 'weather': 7241,
 'like': 4000,
 'food': 2863,
 'do': 2324,
 'social': 6119,
 'support': 6444,
 'system': 6498,
 'friends': 2939,
 'in': 3529,
 'all': 891,
 'these': 6661,
 'things': 6672,
 'are': 1021,
 'important': 3521,
 'yes': 7496,
 'sura': 6448,
 'sun': 6425,
 'tv': 6906,
 'lol': 4069,
 'cant': 1606,
 'pick': 5060,
 'phone': 5046,
 'right': 5631,
 'pls': 5114,
 'send': 5850,
 'message': 4334,
 'probably': 5281,
 'gonna': 3104,
 'be': 1242,
 'here': 3320,
 'for': 2872,
 'while': 7304,
 'see': 5825,
 'later': 3914,
 'tonight': 6787,
 'lt': 4130,
 'hi': 3332,
 'ya': 7472,
 '4goten': 504,
 'bout': 1419,
 'me': 4286,
 'scammers': 5774,
 'getting': 3051,
 'smart': 6079,
 'though': 6690,
 'this': 6679,
 'regular': 5517,
 'vodafone': 7129,
 'no': 4669,
 'if': 3493,
 'respond': 5592,
 'further': 2981,
 'prem': 5237,
 'msg': 4492,
 'subscription': 6390,
 'other': 4869,
 'nos': 4701,
 'used': 7037,
 'also': 906,
 'beware': 1305,
 'we': 7234,
 'made': 4183,
 'it': 3645,
 'eta': 2586,
 'at': 1085,
 'taunton': 6547,
 '12': 270,
 '30': 413,
 'as': 1056,
 'planned': 5095,
 'thatâ': 6641,
 'still': 6309,
 'okday': 4788,
 'good': 3106,
 'xx': 7460,
 'always': 912,
 'online': 4813,
 'on': 4804,
 'yahoo': 7474,
 'would': 7418,
 'with': 7359,
 'someday': 6132,
 'stuff': 6368,
 'sell': 5843,
 'll': 4045,
 'tell': 6582,
 'sorry': 6164,
 'im': 3508,
 'stil': 6308,
 'fucked': 2959,
 'after': 836,
 'last': 3910,
 'nite': 4662,
 'went': 7274,
 'tobed': 6759,
 '430': 474,
 'got': 3122,
 'up': 7004,
 'work': 7399,
 '630': 566,
 'mom': 4441,
 'might': 4349,
 'back': 1168,
 'than': 6625,
 'gt': 3177,
 '123': 275,
 'congratulations': 1925,
 'week': 7254,
 'competition': 1887,
 'draw': 2394,
 'won': 7385,
 '1450': 289,
 'prize': 5275,
 'claim': 1788,
 'just': 3764,
 '09050002311': 162,
 'b4280703': 1153,
 'cs': 2047,
 'sms': 6099,
 '08718727868': 139,
 'over': 4895,
 '18': 309,
 'only': 4815,
 '150ppm': 298,
 'want': 7192,
 'more': 4459,
 'latest': 3915,
 'there': 6659,
 'can': 1597,
 'scrounge': 5801,
 'ammo': 925,
 'give': 3070,
 'new': 4630,
 'ak': 873,
 'try': 6882,
 'goodmorning': 3111,
 'today': 6761,
 'am': 914,
 'late': 3912,
 '2hrs': 383,
 'because': 1252,
 'of': 4763,
 'pain': 4921,
 'truro': 6878,
 'hospital': 3406,
 'ext': 2670,
 'side': 5987,
 'vote': 7138,
 'wherever': 7300,
 'heart': 3292,
 'guides': 3191,
 'short': 5949,
 'but': 1541,
 'cute': 2087,
 'person': 5022,
 'minor': 4374,
 'shindig': 5924,
 'place': 5087,
 'interested': 3594,
 'text': 6614,
 'meet': 4303,
 'someone': 6133,
 'sexy': 5885,
 'date': 2128,
 'or': 4843,
 'even': 2598,
 'flirt': 2833,
 'its': 3651,
 'join': 3726,
 'reply': 5567,
 'name': 4558,
 'age': 844,
 'eg': 2491,
 'sam': 5737,
 '25': 358,
 'recd': 5467,
 'thirtyeight': 6678,
 'pence': 5002,
 'velly': 7081,
 'please': 5106,
 'going': 3097,
 'any': 967,
 'exciting': 2636,
 'karaoke': 3787,
 'type': 6928,
 'activities': 787,
 'debating': 2152,
 'whether': 7302,
 'play': 5099,
 'football': 2868,
 'eve': 2596,
 'feeling': 2746,
 'lazy': 3930,
 'taught': 6546,
 'ranjith': 5418,
 'sir': 6018,
 'called': 1579,
 'so': 6117,
 'becaus': 1251,
 'hes': 3323,
 'verifying': 7085,
 'about': 743,
 'project': 5297,
 'prabu': 5212,
 'told': 6771,
 'pa': 4910,
 'dont': 2363,
 'mistake': 4399,
 'okie': 4790,
 'thanx': 6634,
 'say': 5767,
 'cool': 1961,
 'little': 4037,
 'time': 6723,
 'soon': 6154,
 'means': 4293,
 'think': 6673,
 'teju': 6577,
 'wrong': 7433,
 'number': 4728,
 'mail': 4197,
 'know': 3848,
 'relatives': 5522,
 'coming': 1873,
 'deliver': 2190,
 'costs': 1981,
 'risks': 5645,
 'benefits': 1290,
 'anything': 973,
 'else': 2512,
 'thanks': 6629,
 'ah': 854,
 'lingo': 4015,
 'let': 3972,
 'wot': 7414,
 'earth': 2461,
 'has': 3256,
 'finished': 2799,
 'making': 4208,
 'actually': 790,
 'fuck': 2958,
 'whatever': 7291,
 'an': 937,
 'excuse': 2637,
 'tampa': 6532,
 'point': 5145,
 'before': 1267,
 'yeah': 7486,
 've': 7076,
 'minute': 4377,
 'derek': 2215,
 'done': 2361,
 'class': 1795,
 'ur': 7020,
 'awarded': 1138,
 'city': 1785,
 'break': 1457,
 'could': 1986,
 'win': 7333,
 '200': 337,
 'summer': 6422,
 'shopping': 5947,
 'spree': 6245,
 'every': 2604,
 'wk': 7366,
 'txt': 6917,
 'store': 6329,
 '88039': 684,
 'skilgme': 6038,
 'tscs087147403231winawk': 6889,
 'age16': 845,
 '50perwksub': 530,
 'mum': 4519,
 'ask': 1064,
 'buy': 1545,
 'home': 3378,
 'spoiled': 6228,
 'northampton': 4700,
 'afraid': 832,
 'staying': 6286,
 'skyving': 6048,
 'off': 4764,
 'ho': 3364,
 'around': 1044,
 'wednesday': 7250,
 'fancy': 2712,
 'comedy': 1869,
 'club': 1823,
 'oh': 4781,
 'many': 4230,
 'responsibilities': 5595,
 'happen': 3237,
 'behave': 1273,
 'ok': 4786,
 'need': 4597,
 'big': 1316,
 'belly': 1282,
 'laugh': 3918,
 'tomo': 6776,
 'aathi': 732,
 'lot': 4095,
 'kindly': 3832,
 'us': 7032,
 'our': 4876,
 'documents': 2333,
 'which': 7303,
 'submitted': 6381,
 'loan': 4051,
 'stapati': 6267,
 'future': 2983,
 'tomorrow': 6778,
 'result': 5605,
 'best': 1294,
 'present': 5247,
 'enjoy': 2539,
 'da': 2098,
 'gone': 3103,
 'mad': 4179,
 'pending': 5004,
 'works': 7405,
 'campus': 1595,
 'library': 3982,
 'shhhhh': 5919,
 'nobody': 4672,
 'supposed': 6446,
 'baby': 1162,
 'ive': 3659,
 'was': 7205,
 'wanting': 7195,
 'allday': 894,
 'didnt': 2255,
 'piss': 5079,
 'xxx': 7463,
 'take': 6515,
 'care': 1618,
 'financial': 2791,
 'problem': 5282,
 'help': 3311,
 'nope': 4691,
 'watching': 7218,
 'out': 4879,
 'bored': 1404,
 'uk': 6941,
 'horniest': 3401,
 'dogging': 2346,
 'service': 5869,
 'sex': 5882,
 '2nite': 397,
 'sign': 5991,
 'follow': 2854,
 'instructions': 3588,
 'entry': 2555,
 '69888': 583,
 'nyt': 4743,
 'ec2a': 2473,
 '3lp': 448,
 '150p': 295,
 'god': 3090,
 'google': 3118,
 'nearby': 4587,
 'cliffs': 1809,
 'symptoms': 6495,
 'listening': 4031,
 'songs': 6150,
 'stopped': 6326,
 'beloved': 1284,
 'angry': 944,
 'eerie': 2487,
 'nokia': 4679,
 'tones': 6781,
 '4u': 514,
 'rply': 5683,
 'tone': 6780,
 'title': 6737,
 '8007': 628,
 'dracula': 2390,
 'titles': 6738,
 'ghost': 3055,
 'addamsfa': 794,
 'munsters': 4524,
 'exorcist': 2650,
 'twilight': 6912,
 'www': 7447,
 'getzed': 3052,
 'co': 1835,
 'pobox36504w45wq': 5132,
 'drop': 2413,
 'tank': 6533,
 'holding': 3372,
 'yo': 7506,
 'movie': 4483,
 'netflix': 4618,
 'anybody': 968,
 'asks': 1069,
 'abt': 748,
 'tel': 6578,
 'them': 6650,
 'headin': 3280,
 'towards': 6821,
 'busetop': 1537,
 'hav': 3265,
 'great': 3155,
 'newquay': 4633,
 'postcard': 5190,
 'look': 4078,
 'girls': 3067,
 '1im': 321,
 'talkin': 6526,
 '2marrow': 386,
 'wed': 7247,
 'aha': 855,
 'argh': 1028,
 'why': 7316,
 'town': 6822,
 'curious': 2073,
 'cuz': 2093,
 'asked': 1066,
 'spending': 6209,
 'years': 7488,
 'brother': 1490,
 'his': 3348,
 'family': 2707,
 'lets': 3973,
 'plan': 5092,
 'next': 4638,
 'ready': 5447,
 'then': 6654,
 'yar': 7478,
 'lor': 4087,
 'poor': 5166,
 'thing': 6671,
 'one': 4809,
 'tmr': 6751,
 'brand': 1449,
 'room': 5667,
 'sleep': 6053,
 'bus': 1534,
 'leaves': 3950,
 'reckon': 5482,
 'arrange': 1046,
 'transport': 6844,
 'both': 1412,
 'too': 6791,
 'apes': 981,
 'fight': 2771,
 'death': 2151,
 'keep': 3796,
 'something': 6139,
 'they': 6666,
 'go': 3087,
 'thats': 6640,
 'amp': 930,
 'drive': 2407,
 'coherently': 1846,
 'twenty': 6909,
 'morning': 4463,
 'had': 3207,
 'weekend': 7255,
 'able': 741,
 'raise': 5398,
 'dad': 2101,
 'he': 3277,
 'however': 3425,
 'said': 5727,
 'rest': 5598,
 'available': 1123,
 'mid': 4345,
 'feb': 2739,
 'amount': 929,
 'quite': 5381,
 'hoping': 3399,
 'abiola': 739,
 'must': 4533,
 'taken': 6517,
 'real': 5448,
 'valentine': 7058,
 'first': 2808,
 'man': 4214,
 'account': 768,
 'dry': 2425,
 'trade': 6827,
 'half': 3218,
 'shit': 5932,
 'credit': 2024,
 'card': 1615,
 'customer': 2082,
 'loyalty': 4125,
 'offer': 4768,
 'nokia6650': 4681,
 'mobile': 4422,
 '10': 248,
 'txtauction': 6919,
 'word': 7397,
 'start': 6271,
 '81151': 640,
 'yours': 7521,
 '4t': 509,
 'ctxt': 2060,
 'tc': 6556,
 'mtmsg': 4504,
 'mean': 4289,
 'texting': 6619,
 'yep': 7494,
 'program': 5295,
 're': 5436,
 'slacking': 6050,
 'sent': 5859,
 'sts': 6357,
 'meeting': 4305,
 'five': 2813,
 'related': 5519,
 'arul': 1054,
 'boy': 1436,
 'glad': 3074,
 'wasted': 7212,
 'applebees': 994,
 'nothing': 4709,
 'themob': 6653,
 'comes': 1870,
 'selection': 5839,
 'downloads': 2384,
 'members': 4318,
 'free': 2917,
 'click': 1808,
 'open': 4826,
 'link': 4016,
 'fone': 2861,
 'waiting': 7170,
 'either': 2501,
 'old': 4797,
 'doesnt': 2339,
 'bother': 1413,
 'doing': 2351,
 'settled': 5877,
 'year': 7487,
 'wishin': 7354,
 'gr8': 3134,
 'hurry': 3456,
 'been': 1263,
 'weed': 7253,
 'deficient': 2175,
 'three': 6696,
 'days': 2136,
 'again': 841,
 'address': 799,
 'carlos': 1629,
 'definitely': 2177,
 'mu': 4508,
 'excuses': 2639,
 'hellogorgeous': 3309,
 'hows': 3426,
 'charge': 1697,
 'lst': 4129,
 'nitw': 4665,
 'wen': 7271,
 'texd': 6613,
 'hopeu': 3398,
 'ad': 791,
 'nice': 4642,
 'wkend': 7367,
 'did': 2252,
 'lookin': 4080,
 '4ward': 517,
 '2mrw': 393,
 'luv': 4145,
 'jaz': 3691,
 'dear': 2147,
 'chechi': 1718,
 'aight': 862,
 'write': 7427,
 'put': 5355,
 'dictionary': 2251,
 'mode': 4432,
 'cover': 1999,
 'screen': 5799,
 'hand': 3224,
 'press': 5252,
 'gently': 3038,
 'remove': 5546,
 'interesting': 3595,
 'delay': 2184,
 'masters': 4256,
 'house': 3419,
 'sky': 6045,
 'dark': 2116,
 'liao': 3979,
 'raining': 5397,
 'run': 5702,
 'already': 903,
 'rite': 5646,
 'hee': 3300,
 'letter': 3974,
 'car': 1614,
 'error': 2571,
 'money': 4448,
 'theatre': 6646,
 'come': 1868,
 'motorola': 4475,
 'upto': 7018,
 '12mths': 281,
 '2price': 399,
 'linerental': 4013,
 '500': 522,
 'net': 4616,
 'mins': 4375,
 '100txt': 254,
 'mth': 4502,
 'tooth': 6797,
 'mobileupd8': 4426,
 '08001950382': 53,
 '2optout': 398,
 'd3wv': 2097,
 'bring': 1476,
 'hit': 3350,
 'cash': 1640,
 'another': 955,
 'butt': 1542,
 'idk': 3489,
 'sitting': 6028,
 'shop': 5945,
 'parking': 4953,
 'bawling': 1224,
 'eyes': 2678,
 'feel': 2744,
 'failure': 2696,
 'everything': 2613,
 'wants': 7196,
 'failing': 2694,
 'small': 6077,
 'kid': 3820,
 'boost': 1400,
 'secret': 5815,
 'energy': 2532,
 'somewhere': 6143,
 'beneath': 1288,
 'pale': 4926,
 'moon': 4457,
 'light': 3996,
 'dreams': 2397,
 'true': 6873,
 'goodnite': 3113,
 'sweet': 6477,
 'teaching': 6565,
 'til': 6720,
 'twelve': 6908,
 'lecture': 3953,
 'two': 6916,
 'damn': 2106,
 'working': 7403,
 'haven': 3268,
 'forgotten': 2886,
 'couple': 1993,
 'bucks': 1510,
 'mob': 4420,
 'nok': 4678,
 '87021': 674,
 '1st': 325,
 'txtin': 6920,
 '16': 306,
 'hl': 3354,
 '4info': 505,
 'pookie': 5163,
 'pie': 5068,
 'didn': 2254,
 'wake': 7171,
 'once': 4807,
 'sec': 5811,
 'breaking': 1460,
 'cstore': 2052,
 'congrats': 1923,
 '3g': 445,
 'videophones': 7100,
 '09063458130': 199,
 'videochat': 7099,
 'wid': 7318,
 'mates': 4261,
 'java': 3688,
 'games': 2999,
 'dload': 2321,
 'polyph': 5156,
 'music': 4530,
 'noline': 4683,
 'rentl': 5555,
 'bx420': 1552,
 'ip4': 3619,
 '5we': 551,
 'nah': 4553,
 'should': 5956,
 'mini': 4368,
 'cheetos': 1732,
 'bag': 1173,
 'romcapspam': 5665,
 'everyone': 2609,
 'responding': 5593,
 'presence': 5246,
 'since': 6008,
 'warm': 7199,
 'outgoing': 4885,
 'bringing': 1477,
 'breath': 1461,
 'sunshine': 6432,
 'were': 7277,
 'fredericksburg': 2916,
 'voucher': 7140,
 'holder': 3371,
 'weeks': 7258,
 'pc': 4990,
 'http': 3434,
 'tlp': 6746,
 'expressoffer': 2669,
 'ts': 6885,
 'apply': 997,
 '80062': 627,
 'wanted': 7194,
 'scold': 5784,
 'yest': 7497,
 'zhong': 7544,
 'se': 5805,
 'qing': 5365,
 'b4': 1151,
 'act': 779,
 'cos': 1976,
 'gep': 3042,
 'don': 2359,
 'worry': 7410,
 'march': 4233,
 'ish': 3635,
 'download': 2382,
 'clear': 1803,
 'movies': 4484,
 'dvd': 2447,
 'copies': 1965,
 'happy': 3247,
 'saying': 5769,
 'entered': 2547,
 'cabin': 1560,
 'boss': 1409,
 'felt': 2753,
 'special': 6193,
 'she': 5911,
 'askd': 1065,
 'lunch': 4140,
 'invited': 3612,
 'her': 3319,
 'apartment': 980,
 'hear': 3289,
 'shuhui': 5977,
 'change': 1688,
 'suntec': 6433,
 'steamboat': 6294,
 'noe': 4673,
 'says': 5770,
 'never': 4626,
 'answer': 958,
 'confirm': 1918,
 'deny': 2204,
 'head': 3278,
 'talk': 6523,
 'height': 3302,
 'confidence': 1917,
 'aeronautics': 821,
 'professors': 5292,
 'wer': 7276,
 'calld': 1578,
 'sit': 6023,
 'aeroplane': 822,
 'aftr': 839,
 'sat': 5753,
 'dat': 2126,
 'plane': 5093,
 'ws': 7436,
 'their': 6648,
 'students': 6363,
 'dey': 2236,
 'hurried': 3455,
 'bt': 1506,
 'move': 4480,
 'princess': 5266,
 'eng': 2533,
 'rocking': 5654,
 'ashes': 1059,
 'park': 4950,
 'very': 7088,
 'bad': 1171,
 'girl': 3065,
 'lady': 3883,
 'increase': 3543,
 'chance': 1686,
 'winning': 7344,
 'bangbabes': 1191,
 'order': 4851,
 'receive': 5471,
 'content': 1943,
 'goto': 3126,
 'wap': 7197,
 'bangb': 1190,
 'internet': 3599,
 'menu': 4328,
 'transaction': 6837,
 'created': 2021,
 'gap': 3003,
 'between': 1302,
 'fingers': 2796,
 'who': 7309,
 'fills': 2782,
 'those': 6687,
 'gaps': 3004,
 'wat': 7214,
 'wan': 7187,
 'shut': 5979,
 'omg': 4802,
 'yesterday': 7498,
 'dream': 2396,
 'kids': 3822,
 'boys': 1440,
 'pissed': 5080,
 'being': 1276,
 'mark': 4238,
 'changing': 1691,
 'diapers': 2247,
 'cause': 1651,
 'owed': 4902,
 'face': 2684,
 'thought': 6691,
 'drink': 2402,
 'tap': 6535,
 'spile': 6214,
 'seven': 5879,
 'pub': 5333,
 'gas': 3010,
 'st': 6255,
 'broad': 1484,
 'canal': 1599,
 'pubs': 5336,
 'near': 4586,
 'frankie': 2909,
 'bennys': 1291,
 'warner': 7202,
 'cinema': 1783,
 'video': 7098,
 'handset': 3228,
 '750': 606,
 'anytime': 974,
 'network': 4622,
 'price': 5260,
 'line': 4010,
 'rental': 5553,
 'camcorder': 1591,
 '08000930705': 51,
 'delivery': 2193,
 'okay': 4787,
 'seen': 5832,
 'friday': 2934,
 'wil': 7326,
 'reach': 5437,
 'mapquest': 4232,
 'usf': 7041,
 'dogwood': 2349,
 'thank': 6628,
 'much': 4510,
 'selflessness': 5842,
 'plenty': 5111,
 'lar': 3903,
 'ba': 1156,
 'dao': 2114,
 'pm': 5122,
 'fri': 2933,
 'ard': 1020,
 '515': 535,
 'newest': 4632,
 'harry': 3255,
 'potter': 5198,
 'phoenix': 5045,
 'book': 1392,
 'questions': 5376,
 'among': 926,
 'readers': 5444,
 'hex': 3326,
 'explain': 2662,
 'hmv': 3363,
 'bonus': 1389,
 'pounds': 5201,
 'genuine': 3039,
 'vouchers': 7141,
 'easy': 2467,
 '86688': 672,
 'info': 3559,
 '100percent': 253,
 'com': 1863,
 'thursday': 6709,
 'haha': 3210,
 'really': 5456,
 'deduct': 2168,
 'lesson': 3970,
 'none': 4686,
 'nowhere': 4717,
 'ikno': 3503,
 'doesdiscount': 2337,
 'shitinnit': 5935,
 'awww': 1143,
 'ill': 3505,
 'lonely': 4074,
 'whats': 7292,
 'todays': 6762,
 'favorite': 2732,
 'oyster': 4908,
 'sashimi': 5752,
 'dun': 2439,
 'wait': 7167,
 'stomach': 6315,
 'rumbling': 5700,
 'birthday': 1334,
 'may': 4279,
 'started': 6272,
 'requests': 5575,
 'came': 1592,
 'bed': 1258,
 'double': 2375,
 'coins': 1848,
 'factory': 2687,
 'gotta': 3127,
 'nitros': 4664,
 'completely': 1895,
 'form': 2887,
 'clark': 1793,
 'utter': 7049,
 'waste': 7211,
 'cbe': 1655,
 'chennai': 1734,
 '3mobile': 451,
 ...}

In [39]:
X_train_np = X_train_cv.toarray()
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
np.where(X_train_np[0]!=0)

(array([  88,  105,  259,  548,  702, 1572, 1709, 1714, 1715, 2952, 3017,
        3411, 3683, 4211, 4360, 4575, 4715, 4996, 5421, 5731, 6321, 6622,
        6755], dtype=int64),)

#### Naive Bayes Classifier

In [42]:
model = MultinomialNB()

In [43]:
model.fit(X_train_cv,y_train)

MultinomialNB()

In [46]:
y_pred = model.predict(X_test_cv)

In [49]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1214
           1       0.97      0.93      0.95       179

    accuracy                           0.99      1393
   macro avg       0.98      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393

#### Test on random datapoint

In [52]:
message = {"Upto 20% off on parking, exclusing offer just for you"}

In [53]:
message_cnt = v.transform(message)

model.predict(message_cnt)

array([1], dtype=int64)