In [31]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

corpus = [
    "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

In [32]:
v = TfidfVectorizer()
v.fit(corpus)
transform_output = v.transform(corpus)

In [33]:
print(v.vocabulary_)

{'thor': 25, 'eating': 10, 'pizza': 22, 'loki': 17, 'is': 16, 'ironman': 15, 'ate': 7, 'already': 0, 'apple': 5, 'announcing': 4, 'new': 20, 'iphone': 14, 'tomorrow': 26, 'tesla': 24, 'model': 19, 'google': 12, 'pixel': 21, 'microsoft': 18, 'surface': 23, 'amazon': 2, 'eco': 11, 'dot': 9, 'am': 1, 'biryani': 8, 'and': 3, 'you': 27, 'are': 6, 'grapes': 13}

In [34]:
all_feature_names = v.get_feature_names_out()

for word in all_feature_names:
    idx = v.vocabulary_.get(word)
    
    # get the score
    idf_score = v.idf_[idx]

    print(f"{word} : {idf_score}")

already : 2.386294361119891
am : 2.386294361119891
amazon : 2.386294361119891
and : 2.386294361119891
announcing : 1.2876820724517808
apple : 2.386294361119891
are : 2.386294361119891
ate : 2.386294361119891
biryani : 2.386294361119891
dot : 2.386294361119891
eating : 1.9808292530117262
eco : 2.386294361119891
google : 2.386294361119891
grapes : 2.386294361119891
iphone : 2.386294361119891
ironman : 2.386294361119891
is : 1.1335313926245225
loki : 2.386294361119891
microsoft : 2.386294361119891
model : 2.386294361119891
new : 1.2876820724517808
pixel : 2.386294361119891
pizza : 2.386294361119891
surface : 2.386294361119891
tesla : 2.386294361119891
thor : 2.386294361119891
tomorrow : 1.2876820724517808
you : 2.386294361119891

In [35]:
print(transform_output)

  (0, 0)	0.24266547282843012
  (0, 7)	0.24266547282843012
  (0, 10)	0.4028663647756293
  (0, 15)	0.24266547282843012
  (0, 16)	0.11527032701364155
  (0, 17)	0.24266547282843012
  (0, 22)	0.7279964184852904
  (0, 25)	0.24266547282843012
  (1, 4)	0.30652086071532464
  (1, 5)	0.5680354003049032
  (1, 14)	0.5680354003049032
  (1, 16)	0.26982671076064085
  (1, 20)	0.30652086071532464
  (1, 26)	0.30652086071532464
  (2, 4)	0.30652086071532464
  (2, 16)	0.26982671076064085
  (2, 19)	0.5680354003049032
  (2, 20)	0.30652086071532464
  (2, 24)	0.5680354003049032
  (2, 26)	0.30652086071532464
  (3, 4)	0.30652086071532464
  (3, 12)	0.5680354003049032
  (3, 16)	0.26982671076064085
  (3, 20)	0.30652086071532464
  (3, 21)	0.5680354003049032
  (3, 26)	0.30652086071532464
  (4, 4)	0.30652086071532464
  (4, 16)	0.26982671076064085
  (4, 18)	0.5680354003049032
  (4, 20)	0.30652086071532464
  (4, 23)	0.5680354003049032
  (4, 26)	0.30652086071532464
  (5, 2)	0.4939131624859277
  (5, 4)	0.266523332177098
  (5, 9)	0.4939131624859277
  (5, 11)	0.4939131624859277
  (5, 16)	0.23461735652994203
  (5, 20)	0.266523332177098
  (5, 26)	0.266523332177098
  (6, 1)	0.3379425688198216
  (6, 3)	0.3379425688198216
  (6, 6)	0.3379425688198216
  (6, 8)	0.3379425688198216
  (6, 10)	0.561042708781391
  (6, 13)	0.3379425688198216
  (6, 27)	0.3379425688198216

### use case

In [36]:
import pandas as pd

df = pd.read_csv('Ecommerce_data.csv')

In [37]:
df.head()

                                                Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

In [38]:
df.label.value_counts()

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [39]:
df.shape

(24000, 2)

In [40]:
df['label_num'] = df['label'].map({
    'Household': 0 ,
    'Electronics': 1,
    'Clothing & Accessories': 2,
    'Books': 3
})

In [41]:
df.head()

,Text,label,label_num
0,Urban Ladder Eisner Low Back Study-Office Comp...,Household,0
1,"Contrast living Wooden Decorative Box,Painted ...",Household,0
2,IO Crest SY-PCI40010 PCI RAID Host Controller ...,Electronics,1
3,ISAKAA Baby Socks from Just Born to 8 Years- P...,Clothing & Accessories,2
4,Indira Designer Women's Art Mysore Silk Saree ...,Clothing & Accessories,2

In [42]:
X_train, X_test, Y_train, Y_test = train_test_split(df.Text,df.label_num,test_size=0.2)

In [43]:
len(X_train)

19200

In [44]:
len(X_test)

4800

#### tf-df vectorizer

In [45]:
tf = TfidfVectorizer()

X_train_tf = tf.fit_transform(X_train)
X_test_tf = tf.transform(X_test)

###  Classification Model

In [46]:
clf = DecisionTreeClassifier()
clf.fit(X_train_tf,Y_train)

y_pred = clf.predict(X_test_tf)

In [49]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.93      0.92      1174
           1       0.95      0.94      0.95      1195
           2       0.97      0.96      0.96      1199
           3       0.95      0.96      0.96      1232

    accuracy                           0.95      4800
   macro avg       0.95      0.95      0.95      4800
weighted avg       0.95      0.95      0.95      4800

In [51]:
msg = ["Contrast living Wooden Decorative Box"]

msg_tf = tf.transform(msg)

clf.predict(msg_tf)

array([3], dtype=int64)